"""Synthetic NetCDF sample-data generation.

Creates a small, clearly-labelled *synthetic* ocean dataset for local
development and automated tests. It is NOT real INCOIS data.

Dimensions: time, depth, latitude, longitude
Variables:  temperature, salinity, u, v
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

SYNTHETIC_NOTE = "SYNTHETIC TEST/SAMPLE DATA - not real INCOIS observations or model output"


def create_synthetic_dataset(
    *,
    n_time: int = 8,
    n_depth: int = 5,
    n_lat: int = 10,
    n_lon: int = 12,
    start: str = "2024-01-01",
    seed: int = 42,
) -> xr.Dataset:
    """Build a deterministic synthetic ocean dataset (lazy-safe size)."""
    rng = np.random.default_rng(seed)
    times = pd.date_range(start=start, periods=n_time, freq="D")
    depths = np.array([0.0, 10.0, 20.0, 50.0, 100.0][:n_depth], dtype="float32")
    lats = np.linspace(5.0, 14.0, n_lat, dtype="float32")
    lons = np.linspace(60.0, 71.0, n_lon, dtype="float32")

    t_grid, z_grid, y_grid, x_grid = np.meshgrid(
        np.arange(n_time, dtype="float32"),
        depths,
        lats,
        lons,
        indexing="ij",
    )

    base_temp = 28.0 - 0.06 * z_grid + 0.3 * np.sin(np.pi * y_grid / max(n_lat - 1, 1))
    temperature = (
        base_temp
        + 0.2 * np.sin(2 * np.pi * t_grid / max(n_time, 1))
        + rng.normal(0, 0.05, base_temp.shape).astype("float32")
    ).astype("float32")

    salinity = (
        34.6
        + 0.01 * z_grid
        - 0.15 * np.cos(np.pi * x_grid / max(n_lon - 1, 1))
        + rng.normal(0, 0.02, base_temp.shape).astype("float32")
    ).astype("float32")

    u = (
        0.2 * np.sin(2 * np.pi * x_grid / max(n_lon - 1, 1)) + rng.normal(0, 0.03, base_temp.shape)
    ).astype("float32")
    v = (
        0.15 * np.cos(2 * np.pi * y_grid / max(n_lat - 1, 1)) + rng.normal(0, 0.03, base_temp.shape)
    ).astype("float32")

    # A few deliberate missing cells to exercise NaN handling.
    temperature[0, 0, 0, 0] = np.nan
    salinity[-1, -1, -1, -1] = np.nan

    ds = xr.Dataset(
        data_vars={
            "temperature": (("time", "depth", "latitude", "longitude"), temperature),
            "salinity": (("time", "depth", "latitude", "longitude"), salinity),
            "u": (("time", "depth", "latitude", "longitude"), u),
            "v": (("time", "depth", "latitude", "longitude"), v),
        },
        coords={
            "time": times,
            "depth": ("depth", depths, {"units": "m", "positive": "down"}),
            "latitude": ("latitude", lats, {"units": "degrees_north"}),
            "longitude": ("longitude", lons, {"units": "degrees_east"}),
        },
        attrs={
            "title": "EchoShield synthetic ocean sample dataset",
            "summary": SYNTHETIC_NOTE,
            "institution": "EchoShield project",
            "source": "Generated by app.testing_utils.create_synthetic_dataset",
            "Conventions": "CF-1.10",
        },
    )
    for name in ("temperature", "salinity", "u", "v"):
        ds[name].attrs.update(
            {
                "temperature": {
                    "long_name": "Sea water temperature",
                    "standard_name": "sea_water_temperature",
                    "units": "degC",
                },
                "salinity": {
                    "long_name": "Sea water practical salinity",
                    "standard_name": "sea_water_practical_salinity",
                    "units": "1e-3",
                },
                "u": {
                    "long_name": "Eastward sea water velocity",
                    "standard_name": "eastward_sea_water_velocity",
                    "units": "m s-1",
                },
                "v": {
                    "long_name": "Northward sea water velocity",
                    "standard_name": "northward_sea_water_velocity",
                    "units": "m s-1",
                },
            }[name]
        )
    return ds


def write_synthetic_netcdf(path: str | Path, **kwargs: object) -> Path:
    """Write the synthetic dataset to ``path`` and return it."""
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    ds = create_synthetic_dataset(**kwargs)  # type: ignore[arg-type]
    encoding = {name: {"zlib": True, "complevel": 4} for name in ds.data_vars}
    ds.to_netcdf(destination, engine="netcdf4", encoding=encoding)
    ds.close()
    return destination
